version: "3"

volumes:
  db:
  logs:

name: tasks_manager
services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5555:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh db python3.12 -m app
    restart: always
    env_file:
      - .env
    volumes:
      - "./logs:/logs"
      - "./images:/images"
    ports:
      - "3333:3333"
    depends_on:
      - db

  worker:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - "./images:/images"
    depends_on:
      - api
      - redis

  flower:
    build: .
    command: celery -A app.worker.celery flower --port=5001
    ports:
      - 5001:5001
    env_file:
      - .env
    depends_on:
      - api
      - redis 


  redis:
    image: redis:7
